if(NOT DEFINED NOMAD_CHAT)
  message(FATAL_ERROR "NOMAD_CHAT executable path is required")
endif()
set(tmp "$ENV{TMPDIR}/nomad-chat-cmake-test")
if(tmp STREQUAL "/nomad-chat-cmake-test")
  set(tmp "/tmp/nomad-chat-cmake-test")
endif()
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}")
execute_process(COMMAND "${NOMAD_CHAT}" init "${tmp}/identity" RESULT_VARIABLE r OUTPUT_VARIABLE address OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT r EQUAL 0 OR NOT address MATCHES "^[0-9a-f][0-9a-f]+$")
  message(FATAL_ERROR "init failed: ${r} ${address}")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" address "${tmp}/identity" RESULT_VARIABLE r OUTPUT_VARIABLE address2 OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT r EQUAL 0 OR NOT address STREQUAL address2)
  message(FATAL_ERROR "address mismatch")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" pack "${tmp}/identity" "${address}" "hello" "${tmp}/message.lxm" RESULT_VARIABLE r)
if(NOT r EQUAL 0)
  message(FATAL_ERROR "pack failed")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" unpack "${tmp}/message.lxm" RESULT_VARIABLE r OUTPUT_VARIABLE inspect)
if(NOT r EQUAL 0 OR NOT inspect MATCHES "content: hello")
  message(FATAL_ERROR "unpack failed: ${inspect}")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" send-file "${tmp}/message.lxm" RESULT_VARIABLE r ERROR_VARIABLE unsupported)
if(NOT r EQUAL 69 OR NOT unsupported MATCHES "not implemented")
  message(FATAL_ERROR "send-file did not fail safely")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" nodes --json "${tmp}/missing.nodes" RESULT_VARIABLE r ERROR_VARIABLE nodes_error)
if(NOT r EQUAL 65 OR NOT nodes_error MATCHES "cannot open node registry")
  message(FATAL_ERROR "nodes missing-store handling failed: ${r} ${nodes_error}")
endif()
file(REMOVE_RECURSE "${tmp}")
