if(NOT DEFINED NOMAD_CHAT)
  message(FATAL_ERROR "NOMAD_CHAT executable path is required")
endif()
set(tmp "$ENV{TMPDIR}/nomad-chat-cmake-test")
if(tmp STREQUAL "/nomad-chat-cmake-test")
  set(tmp "/tmp/nomad-chat-cmake-test")
endif()
file(REMOVE_RECURSE "${tmp}")
file(MAKE_DIRECTORY "${tmp}")
execute_process(COMMAND "${NOMAD_CHAT}" init "${tmp}/identity" RESULT_VARIABLE r OUTPUT_VARIABLE address OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT r EQUAL 0 OR NOT address MATCHES "^[0-9a-f][0-9a-f]+$")
  message(FATAL_ERROR "init failed: ${r} ${address}")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" address "${tmp}/identity" RESULT_VARIABLE r OUTPUT_VARIABLE address2 OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT r EQUAL 0 OR NOT address STREQUAL address2)
  message(FATAL_ERROR "address mismatch")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" public "${tmp}/identity" RESULT_VARIABLE r OUTPUT_VARIABLE public OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT r EQUAL 0 OR NOT public MATCHES "^[0-9a-f][0-9a-f]+$" OR NOT public MATCHES "^................................................................................................................................$")
  message(FATAL_ERROR "public identity inspection failed")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" paper-export "${tmp}/identity" "${address}" "${public}" "paper hello" RESULT_VARIABLE r OUTPUT_VARIABLE uri OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_VARIABLE paper_error)
if(NOT r EQUAL 0 OR NOT uri MATCHES "^lxm://")
  message(FATAL_ERROR "paper export failed: ${r} ${paper_error}")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" paper-import --json "${tmp}/identity" "${public}" "${tmp}/paper.store" "${uri}" RESULT_VARIABLE r OUTPUT_VARIABLE imported ERROR_VARIABLE paper_error)
if(NOT r EQUAL 0 OR NOT imported MATCHES "\"content\":\"paper hello\"" OR NOT imported MATCHES "\"signature\":\"verified\"" OR NOT imported MATCHES "\"duplicate\":false")
  message(FATAL_ERROR "paper import failed: ${r} ${imported} ${paper_error}")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" paper-import --json "${tmp}/identity" "${public}" "${tmp}/paper.store" "${uri}" RESULT_VARIABLE r OUTPUT_VARIABLE duplicate ERROR_VARIABLE paper_error)
if(NOT r EQUAL 0 OR NOT duplicate MATCHES "\"duplicate\":true")
  message(FATAL_ERROR "paper duplicate handling failed: ${r} ${duplicate} ${paper_error}")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" paper-export --json "${tmp}/identity" "${address}" "${public}" "unknown source" RESULT_VARIABLE r OUTPUT_VARIABLE exported_json ERROR_VARIABLE paper_error)
string(REGEX REPLACE ".*\"uri\":\"([^\"]+)\".*" "\\1" unknown_uri "${exported_json}")
if(NOT r EQUAL 0 OR NOT exported_json MATCHES "\"message_id\":" OR NOT unknown_uri MATCHES "^lxm://")
  message(FATAL_ERROR "JSON paper export failed: ${r} ${exported_json} ${paper_error}")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" paper-import --json "${tmp}/identity" - "${tmp}/unknown.store" "${unknown_uri}" RESULT_VARIABLE r OUTPUT_VARIABLE unknown ERROR_VARIABLE paper_error)
if(NOT r EQUAL 0 OR NOT unknown MATCHES "\"signature\":\"unverified\"" OR NOT unknown MATCHES "\"content\":\"unknown source\"")
  message(FATAL_ERROR "unknown paper source handling failed: ${r} ${unknown} ${paper_error}")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" paper-import "${tmp}/identity" "${public}" "${tmp}/bad.store" "lxmf://AAAA" RESULT_VARIABLE r ERROR_VARIABLE paper_error)
if(NOT r EQUAL 65 OR NOT paper_error MATCHES "paper import failed")
  message(FATAL_ERROR "malformed paper URI was not rejected: ${r} ${paper_error}")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" init "${tmp}/other.identity" RESULT_VARIABLE r OUTPUT_QUIET)
if(NOT r EQUAL 0)
  message(FATAL_ERROR "second identity creation failed")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" public "${tmp}/other.identity" RESULT_VARIABLE r OUTPUT_VARIABLE other_public OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT r EQUAL 0)
  message(FATAL_ERROR "second public identity inspection failed")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" paper-import "${tmp}/identity" "${other_public}" "${tmp}/wrong-source.store" "${uri}" RESULT_VARIABLE r ERROR_VARIABLE paper_error)
if(NOT r EQUAL 65 OR NOT paper_error MATCHES "source public key does not match")
  message(FATAL_ERROR "incorrect paper source was not rejected: ${r} ${paper_error}")
endif()
string(REPEAT "x" 3000 oversized)
execute_process(COMMAND "${NOMAD_CHAT}" paper-export "${tmp}/identity" "${address}" "${public}" "${oversized}" RESULT_VARIABLE r ERROR_VARIABLE paper_error)
if(NOT r EQUAL 65 OR NOT paper_error MATCHES "paper export failed")
  message(FATAL_ERROR "oversized paper message was not rejected: ${r} ${paper_error}")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" pack "${tmp}/identity" "${address}" "hello" "${tmp}/message.lxm" RESULT_VARIABLE r)
if(NOT r EQUAL 0)
  message(FATAL_ERROR "pack failed")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" unpack "${tmp}/message.lxm" RESULT_VARIABLE r OUTPUT_VARIABLE inspect)
if(NOT r EQUAL 0 OR NOT inspect MATCHES "content: hello")
  message(FATAL_ERROR "unpack failed: ${inspect}")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" send-file "${tmp}/message.lxm" RESULT_VARIABLE r ERROR_VARIABLE unsupported)
if(NOT r EQUAL 69 OR NOT unsupported MATCHES "not implemented")
  message(FATAL_ERROR "send-file did not fail safely")
endif()
execute_process(COMMAND "${NOMAD_CHAT}" nodes --json "${tmp}/missing.nodes" RESULT_VARIABLE r ERROR_VARIABLE nodes_error)
if(NOT r EQUAL 65 OR NOT nodes_error MATCHES "cannot open node registry")
  message(FATAL_ERROR "nodes missing-store handling failed: ${r} ${nodes_error}")
endif()
file(REMOVE_RECURSE "${tmp}")
