#include "reticulum/micron.h"
#include <string.h>
#include <ctype.h>
#include <stdio.h>
static int copy_url(char *o,size_t c,const char *s){size_t n=strlen(s);if(!o||!s||n+1>c)return 0;memcpy(o,s,n+1);return 1;}
static void trim(char *s){size_t n=strlen(s);while(n&&isspace((unsigned char)s[n-1]))s[--n]=0;size_t i=0;while(isspace((unsigned char)s[i]))i++;if(i)memmove(s,s+i,n-i+1);}
int rns_micron_parse(rns_micron_page *p,const uint8_t *data,size_t len){if(!p||(!data&&len))return 0;memset(p,0,sizeof(*p));size_t start=0;while(start<len&&p->count<RNS_MICRON_MAX_ITEMS){size_t end=start;while(end<len&&data[end]!='\n')end++;size_t n=end-start;if(n>=RNS_MICRON_TEXT_MAX)n=RNS_MICRON_TEXT_MAX-1;char line[RNS_MICRON_TEXT_MAX];memcpy(line,data+start,n);line[n]=0;trim(line);if(line[0]){rns_micron_item *i=&p->items[p->count++];i->kind=RNS_MICRON_TEXT; if(line[0]=='#'){i->kind=RNS_MICRON_HEADING;size_t k=0;while(line[k]=='#')k++;memmove(line,line+k,strlen(line)-k+1);trim(line);}else if(!strncmp(line,"[",1)){char *q=strchr(line,']');char *o=q?strstr(q,"("):NULL; if(q&&o){i->kind=RNS_MICRON_LINK;*q=0;*o=0;snprintf(i->text,sizeof i->text,"%s",line+1);snprintf(i->target,sizeof i->target,"%s",q+2);size_t z=strlen(i->target);if(z&&i->target[z-1]==')')i->target[z-1]=0;}else snprintf(i->text,sizeof i->text,"%s",line);}else if(!strncmp(line,"!media ",7)){i->kind=RNS_MICRON_MEDIA;i->unsupported=true;snprintf(i->target,sizeof i->target,"%s",line+7);}else if(!strncmp(line,"input ",6)){i->kind=RNS_MICRON_INPUT;snprintf(i->target,sizeof i->target,"%s",line+6);}else if(!strncmp(line,"button ",7)){i->kind=RNS_MICRON_BUTTON;snprintf(i->text,sizeof i->text,"%s",line+7);}else snprintf(i->text,sizeof i->text,"%s",line);}start=end<len?end+1:end;}return start==len;}
int rns_micron_normalize_url(const char *base,const char *target,char *out,size_t cap){if(!target||!out||!cap)return 0;if(strstr(target,"://")||!strncmp(target,"lxmf:",5))return copy_url(out,cap,target);if(!base)return copy_url(out,cap,target);char root[RNS_MICRON_TEXT_MAX];if(!copy_url(root,sizeof root,base))return 0;char *slash=strrchr(root,'/');if(target[0]=='/'){char *scheme=strstr(root,"://");slash=scheme?strchr(scheme+3,'/'):strchr(root,'/');}if(slash)slash[1]=0;else root[0]=0;char joined[RNS_MICRON_TEXT_MAX];if(snprintf(joined,sizeof joined,"%s%s",root,target)<0)return 0;return copy_url(out,cap,joined);}
void rns_micron_history_init(rns_micron_history *h){if(h)memset(h,0,sizeof(*h));}
int rns_micron_history_push(rns_micron_history *h,const char *url){if(!h||!url||strlen(url)>=RNS_MICRON_TEXT_MAX)return 0;if(h->count&&h->cursor<h->count&&!strcmp(h->urls[h->cursor],url))return 1;if(h->cursor+1<h->count)h->count=h->cursor+1;if(h->count==32){memmove(h->urls,h->urls+1,sizeof(h->urls[0])*31);h->count=31;}memcpy(h->urls[h->count],url,strlen(url)+1);h->cursor=h->count++;return 1;}
const char *rns_micron_history_back(rns_micron_history *h){if(!h||h->count==0||h->cursor==0)return NULL;return h->urls[--h->cursor];}
const char *rns_micron_history_forward(rns_micron_history *h){if(!h||h->cursor+1>=h->count)return NULL;return h->urls[++h->cursor];}
