#include "reticulum/lxmf_router.h"

#include <string.h>

typedef struct { uint8_t *p; size_t n; } wr;
typedef struct { const uint8_t *p; const uint8_t *end; } rd;

static bool put(wr *w,const void *p,size_t n){if(n>w->n)return false;memcpy(w->p,p,n);w->p+=n;w->n-=n;return true;}
static bool byte(wr *w,uint8_t b){return put(w,&b,1);}
static bool encode_bin(wr *w,const uint8_t *p,size_t n){if(n<=255){uint8_t h[2]={0xc4,(uint8_t)n};return put(w,h,2)&&put(w,p,n);}uint8_t h[3]={0xc5,(uint8_t)(n>>8),(uint8_t)n};return n<=65535&&put(w,h,3)&&put(w,p,n);}

static bool valid_utf8(const uint8_t *s,size_t n){size_t i=0;while(i<n){uint8_t c=s[i++];if(c<0x80)continue;unsigned more;uint32_t cp;if((c&0xe0)==0xc0){more=1;cp=c&0x1f;if(cp<2)return false;}else if((c&0xf0)==0xe0){more=2;cp=c&0x0f;}else if((c&0xf8)==0xf0){more=3;cp=c&7;}else return false;if(i+more>n)return false;for(unsigned j=0;j<more;j++){uint8_t d=s[i++];if((d&0xc0)!=0x80)return false;cp=(cp<<6)|(d&0x3f);}if(cp>0x10ffff||(cp>=0xd800&&cp<=0xdfff)||(more==2&&cp<0x800)||(more==3&&cp<0x10000))return false;}return true;}

lxmf_status_t lxmf_announce_encode(const lxmf_announce_data_t *d,uint8_t *out,size_t cap,size_t *out_len){if(!d||!out||!out_len||d->display_name_len>LXMF_DISPLAY_NAME_MAX||!valid_utf8((const uint8_t *)d->display_name,d->display_name_len)||(d->has_stamp_cost&&(d->stamp_cost<1||d->stamp_cost>254)))return LXMF_ERR_ARGUMENT;wr w={out,cap};if(!byte(&w,0x93)||!encode_bin(&w,(const uint8_t *)d->display_name,d->display_name_len))return LXMF_ERR_BOUNDS;if(d->has_stamp_cost){if(d->stamp_cost<=127){if(!byte(&w,d->stamp_cost))return LXMF_ERR_BOUNDS;}else{uint8_t v[2]={0xcc,d->stamp_cost};if(!put(&w,v,2))return LXMF_ERR_BOUNDS;}}else if(!byte(&w,0xc0))return LXMF_ERR_BOUNDS;if(!byte(&w,0x91)||!byte(&w,0x00))return LXMF_ERR_BOUNDS;*out_len=cap-w.n;return LXMF_OK;}

static bool take(rd *r,size_t n,const uint8_t **p){if(n>(size_t)(r->end-r->p))return false;*p=r->p;r->p+=n;return true;}
static bool parse_bytes(rd *r,const uint8_t **p,size_t *n){if(r->p>=r->end)return false;uint8_t c=*r->p++;size_t len;if((c&0xe0)==0xa0)len=c&31;else if(c==0xc4||c==0xd9){if(r->p>=r->end)return false;len=*r->p++;}else if(c==0xc5||c==0xda){if(r->end-r->p<2)return false;len=((size_t)r->p[0]<<8)|r->p[1];r->p+=2;}else return false;*n=len;return take(r,len,p);}
static bool parse_uint(rd *r,uint8_t *v){if(r->p>=r->end)return false;uint8_t c=*r->p++;if(c<=0x7f){*v=c;return true;}if(c==0xcc&&r->p<r->end){*v=*r->p++;return true;}return false;}
static bool skip(rd *r,unsigned depth){if(depth>16||r->p>=r->end)return false;uint8_t c=*r->p++;if(c<=0x7f||c>=0xe0||c==0xc0||c==0xc2||c==0xc3)return true;size_t n=0;unsigned items=0;if((c&0xe0)==0xa0)n=c&31;else if((c&0xf0)==0x90)items=c&15;else if((c&0xf0)==0x80)items=2*(c&15);else if(c==0xc4||c==0xd9){if(r->p>=r->end)return false;n=*r->p++;}else if(c==0xc5||c==0xda){if(r->end-r->p<2)return false;n=((size_t)r->p[0]<<8)|r->p[1];r->p+=2;}else if(c==0xcc||c==0xd0)n=1;else if(c==0xcd||c==0xd1)n=2;else if(c==0xce||c==0xd2||c==0xca)n=4;else if(c==0xcf||c==0xd3||c==0xcb)n=8;else return false;if(n>(size_t)(r->end-r->p))return false;r->p+=n;for(unsigned i=0;i<items;i++)if(!skip(r,depth+1))return false;return true;}

lxmf_status_t lxmf_announce_parse(const uint8_t *in,size_t len,lxmf_announce_data_t *d){if(!in||!d||len==0)return LXMF_ERR_ARGUMENT;memset(d,0,sizeof *d);if((in[0]&0xf0)!=0x90&&in[0]!=0xdc){if(len>LXMF_DISPLAY_NAME_MAX||!valid_utf8(in,len))return LXMF_ERR_FORMAT;memcpy(d->display_name,in,len);d->display_name[len]='\0';d->display_name_len=len;d->features=LXMF_FEATURE_COMPRESSION;return LXMF_OK;}rd r={in,in+len};size_t count;if((*r.p&0xf0)==0x90)count=*r.p++&15;else{r.p++;if(r.end-r.p<2)return LXMF_ERR_FORMAT;count=((size_t)r.p[0]<<8)|r.p[1];r.p+=2;}if(count<1)return LXMF_ERR_FORMAT;const uint8_t *name;size_t name_len;if(!parse_bytes(&r,&name,&name_len)||name_len>LXMF_DISPLAY_NAME_MAX||!valid_utf8(name,name_len))return LXMF_ERR_FORMAT;memcpy(d->display_name,name,name_len);d->display_name[name_len]='\0';d->display_name_len=name_len;if(count>=2){if(r.p>=r.end)return LXMF_ERR_FORMAT;if(*r.p==0xc0)r.p++;else{uint8_t cost;if(!parse_uint(&r,&cost)||cost<1||cost>254)return LXMF_ERR_FORMAT;d->has_stamp_cost=true;d->stamp_cost=cost;}}if(count>=3){if(r.p>=r.end)return LXMF_ERR_FORMAT;size_t fc;if((*r.p&0xf0)==0x90)fc=*r.p++&15;else if(*r.p==0xdc){r.p++;if(r.end-r.p<2)return LXMF_ERR_FORMAT;fc=((size_t)r.p[0]<<8)|r.p[1];r.p+=2;}else return LXMF_ERR_FORMAT;for(size_t i=0;i<fc;i++){uint8_t f;if(!parse_uint(&r,&f))return LXMF_ERR_FORMAT;if(f==0)d->features|=LXMF_FEATURE_COMPRESSION;}}else d->features=LXMF_FEATURE_COMPRESSION;for(size_t i=3;i<count;i++)if(!skip(&r,0))return LXMF_ERR_FORMAT;if(r.p!=r.end)return LXMF_ERR_FORMAT;return LXMF_OK;}

lxmf_status_t lxmf_contact_book_init(lxmf_contact_book_t *b,lxmf_contact_t *storage,size_t cap,lxmf_clock_fn clock,void *ctx){if(!b||!storage||cap==0||!clock)return LXMF_ERR_ARGUMENT;memset(storage,0,cap*sizeof *storage);b->entries=storage;b->capacity=cap;b->count=0;b->clock=clock;b->clock_context=ctx;return LXMF_OK;}
const lxmf_contact_t *lxmf_contact_book_lookup(const lxmf_contact_book_t *b,const uint8_t hash[16]){if(!b||!hash)return NULL;for(size_t i=0;i<b->capacity;i++)if(b->entries[i].used&&memcmp(b->entries[i].delivery_hash,hash,16)==0)return &b->entries[i];return NULL;}
lxmf_status_t lxmf_contact_book_update(lxmf_contact_book_t *b,const uint8_t hash[16],const uint8_t pub[64],const lxmf_announce_data_t *a){if(!b||!hash||!pub||!a||!b->clock||a->display_name_len>LXMF_DISPLAY_NAME_MAX||!valid_utf8((const uint8_t *)a->display_name,a->display_name_len)||(a->has_stamp_cost&&(a->stamp_cost<1||a->stamp_cost>254)))return LXMF_ERR_ARGUMENT;lxmf_contact_t *slot=NULL;for(size_t i=0;i<b->capacity;i++){if(b->entries[i].used&&memcmp(b->entries[i].delivery_hash,hash,16)==0){slot=&b->entries[i];break;}if(!slot&&!b->entries[i].used)slot=&b->entries[i];}if(!slot)return LXMF_ERR_BOUNDS;bool fresh=!slot->used;memset(slot,0,sizeof *slot);slot->used=true;memcpy(slot->delivery_hash,hash,16);memcpy(slot->identity_public,pub,64);memcpy(slot->display_name,a->display_name,a->display_name_len);slot->display_name[a->display_name_len]='\0';slot->display_name_len=a->display_name_len;slot->has_stamp_cost=a->has_stamp_cost;slot->stamp_cost=a->stamp_cost;slot->features=a->features;slot->last_seen=b->clock(b->clock_context);if(fresh)b->count++;return LXMF_OK;}
size_t lxmf_contact_book_expire(lxmf_contact_book_t *b,uint64_t max_age){if(!b||!b->clock)return 0;uint64_t now=b->clock(b->clock_context);size_t n=0;for(size_t i=0;i<b->capacity;i++)if(b->entries[i].used&&now>=b->entries[i].last_seen&&now-b->entries[i].last_seen>max_age){memset(&b->entries[i],0,sizeof b->entries[i]);b->count--;n++;}return n;}
