#include "reticulum/lxmf_store.h"

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#define HEADER_SIZE 16u
#define PUT_FIXED 77u
#define STATUS_SIZE 33u
#define TYPE_PUT 1u
#define TYPE_STATUS 2u

typedef struct { uint8_t id[32]; uint64_t offset; uint32_t content_len; uint8_t status; } index_entry;
typedef struct { FILE *file; char path[LXMF_STORE_PATH_MAX+1]; index_entry index[LXMF_STORE_MAX_MESSAGES]; size_t count; } store_impl;

static void put32(uint8_t *p,uint32_t v){p[0]=(uint8_t)(v>>24);p[1]=(uint8_t)(v>>16);p[2]=(uint8_t)(v>>8);p[3]=(uint8_t)v;}
static uint32_t get32(const uint8_t *p){return ((uint32_t)p[0]<<24)|((uint32_t)p[1]<<16)|((uint32_t)p[2]<<8)|p[3];}
static void put64(uint8_t *p,uint64_t v){for(unsigned i=0;i<8;i++)p[7-i]=(uint8_t)(v>>(8*i));}
static uint64_t get64(const uint8_t *p){uint64_t v=0;for(unsigned i=0;i<8;i++)v=(v<<8)|p[i];return v;}
static uint32_t crc32_bytes(const uint8_t *p,size_t n){uint32_t c=0xffffffffu;while(n--){c^=*p++;for(unsigned i=0;i<8;i++)c=(c>>1)^(0xedb88320u&(~(c&1u)+1u));}return ~c;}
static bool valid_status(uint8_t s){return s<=LXMF_DELIVERY_FAILED;}
static index_entry *find(store_impl *s,const uint8_t id[32]){for(size_t i=0;i<s->count;i++)if(memcmp(s->index[i].id,id,32)==0)return &s->index[i];return NULL;}
static lxmf_status_t sync_file(FILE *f){if(fflush(f)!=0)return LXMF_ERR_CRYPTO;return fsync(fileno(f))==0?LXMF_OK:LXMF_ERR_CRYPTO;}
static lxmf_status_t append_record(store_impl *s,uint8_t type,const uint8_t *payload,uint32_t n,uint64_t *offset){if(fseek(s->file,0,SEEK_END)!=0)return LXMF_ERR_CRYPTO;long pos=ftell(s->file);if(pos<0||(uint64_t)pos+HEADER_SIZE+n>LXMF_STORE_MAX_FILE_SIZE)return LXMF_ERR_BOUNDS;uint8_t h[HEADER_SIZE]={'L','X','M','S',1,type,0,0};put32(h+8,n);put32(h+12,crc32_bytes(payload,n));if(fwrite(h,1,sizeof h,s->file)!=sizeof h||fwrite(payload,1,n,s->file)!=n)return LXMF_ERR_CRYPTO;lxmf_status_t st=sync_file(s->file);if(st==LXMF_OK&&offset)*offset=(uint64_t)pos;return st;}

static lxmf_status_t scan(store_impl *s){s->count=0;if(fseek(s->file,0,SEEK_SET)!=0)return LXMF_ERR_CRYPTO;uint64_t good=0;for(;;){uint8_t h[HEADER_SIZE];size_t got=fread(h,1,sizeof h,s->file);if(got==0&&feof(s->file))break;if(got!=sizeof h)goto recover;if(memcmp(h,"LXMS",4)!=0||h[4]!=1||(h[5]!=TYPE_PUT&&h[5]!=TYPE_STATUS))goto recover;uint32_t n=get32(h+8);if(n>PUT_FIXED+LXMF_STORE_MAX_CONTENT||n==0)goto recover;uint8_t payload[PUT_FIXED+LXMF_STORE_MAX_CONTENT];if(fread(payload,1,n,s->file)!=n||crc32_bytes(payload,n)!=get32(h+12))goto recover;if(h[5]==TYPE_PUT){if(n<PUT_FIXED||get32(payload+73)!=n-PUT_FIXED||!valid_status(payload[72]))goto recover;index_entry *e=find(s,payload);if(!e){if(s->count>=LXMF_STORE_MAX_MESSAGES)return LXMF_ERR_BOUNDS;e=&s->index[s->count++];memcpy(e->id,payload,32);e->offset=good;e->content_len=n-PUT_FIXED;}e->status=payload[72];}else{if(n!=STATUS_SIZE||!valid_status(payload[32]))goto recover;index_entry *e=find(s,payload);if(e)e->status=payload[32];}good+=HEADER_SIZE+n;}clearerr(s->file);return LXMF_OK;
recover: clearerr(s->file);if(ftruncate(fileno(s->file),(off_t)good)!=0)return LXMF_ERR_CRYPTO;if(fseek(s->file,0,SEEK_END)!=0)return LXMF_ERR_CRYPTO;return sync_file(s->file);}

lxmf_status_t lxmf_store_open(lxmf_store_t *store,const char *path){if(!store||!path||store->implementation||strlen(path)>LXMF_STORE_PATH_MAX)return LXMF_ERR_ARGUMENT;store_impl *s=calloc(1,sizeof *s);if(!s)return LXMF_ERR_BOUNDS;memcpy(s->path,path,strlen(path)+1);s->file=fopen(path,"a+b");if(!s->file){free(s);return LXMF_ERR_CRYPTO;}store->implementation=s;lxmf_status_t st=scan(s);if(st!=LXMF_OK){lxmf_store_close(store);return st;}return LXMF_OK;}
void lxmf_store_close(lxmf_store_t *store){if(!store||!store->implementation)return;store_impl *s=store->implementation;if(s->file)fclose(s->file);free(s);store->implementation=NULL;}
size_t lxmf_store_count(const lxmf_store_t *store){return store&&store->implementation?((store_impl *)store->implementation)->count:0;}

lxmf_status_t lxmf_store_put(lxmf_store_t *store,const lxmf_store_message_t *m,bool *inserted){if(inserted)*inserted=false;if(!store||!store->implementation||!m||m->content.len>LXMF_STORE_MAX_CONTENT||(m->content.len&&!m->content.data)||!valid_status((uint8_t)m->status))return LXMF_ERR_ARGUMENT;store_impl *s=store->implementation;if(find(s,m->message_id)){return LXMF_OK;}if(s->count>=LXMF_STORE_MAX_MESSAGES)return LXMF_ERR_BOUNDS;uint32_t n=(uint32_t)(PUT_FIXED+m->content.len);uint8_t payload[PUT_FIXED+LXMF_STORE_MAX_CONTENT];memcpy(payload,m->message_id,32);memcpy(payload+32,m->destination,16);memcpy(payload+48,m->source,16);uint64_t bits;memcpy(&bits,&m->timestamp,8);put64(payload+64,bits);payload[72]=(uint8_t)m->status;put32(payload+73,(uint32_t)m->content.len);memcpy(payload+PUT_FIXED,m->content.data,m->content.len);uint64_t offset;lxmf_status_t st=append_record(s,TYPE_PUT,payload,n,&offset);if(st!=LXMF_OK)return st;index_entry *e=&s->index[s->count++];memcpy(e->id,m->message_id,32);e->offset=offset;e->content_len=(uint32_t)m->content.len;e->status=(uint8_t)m->status;if(inserted)*inserted=true;return LXMF_OK;}
lxmf_status_t lxmf_store_update_status(lxmf_store_t *store,const uint8_t id[32],lxmf_delivery_status_t status){if(!store||!store->implementation||!id||!valid_status((uint8_t)status))return LXMF_ERR_ARGUMENT;store_impl *s=store->implementation;index_entry *e=find(s,id);if(!e)return LXMF_ERR_FORMAT;if(e->status==(uint8_t)status)return LXMF_OK;uint8_t p[STATUS_SIZE];memcpy(p,id,32);p[32]=(uint8_t)status;lxmf_status_t st=append_record(s,TYPE_STATUS,p,sizeof p,NULL);if(st==LXMF_OK)e->status=(uint8_t)status;return st;}
lxmf_status_t lxmf_store_read(lxmf_store_t *store,const uint8_t id[32],lxmf_store_message_t *m,uint8_t *content,size_t cap){if(!store||!store->implementation||!id||!m)return LXMF_ERR_ARGUMENT;store_impl *s=store->implementation;index_entry *e=find(s,id);if(!e)return LXMF_ERR_FORMAT;if(e->content_len>cap||(e->content_len&&!content))return LXMF_ERR_BOUNDS;if(fseek(s->file,(long)(e->offset+HEADER_SIZE),SEEK_SET)!=0)return LXMF_ERR_CRYPTO;uint8_t fixed[PUT_FIXED];if(fread(fixed,1,sizeof fixed,s->file)!=sizeof fixed)return LXMF_ERR_CRYPTO;memset(m,0,sizeof *m);memcpy(m->message_id,fixed,32);memcpy(m->destination,fixed+32,16);memcpy(m->source,fixed+48,16);uint64_t bits=get64(fixed+64);memcpy(&m->timestamp,&bits,8);m->status=(lxmf_delivery_status_t)e->status;m->content.data=content;m->content.len=e->content_len;if(e->content_len&&fread(content,1,e->content_len,s->file)!=e->content_len)return LXMF_ERR_CRYPTO;return LXMF_OK;}
lxmf_status_t lxmf_store_list(lxmf_store_t *store,lxmf_store_list_fn cb,void *ctx){if(!store||!store->implementation||!cb)return LXMF_ERR_ARGUMENT;store_impl *s=store->implementation;uint8_t content[LXMF_STORE_MAX_CONTENT];for(size_t i=0;i<s->count;i++){lxmf_store_message_t m;lxmf_status_t st=lxmf_store_read(store,s->index[i].id,&m,content,sizeof content);if(st!=LXMF_OK)return st;if(!cb(ctx,&m))break;}return LXMF_OK;}

lxmf_status_t lxmf_store_compact(lxmf_store_t *store){if(!store||!store->implementation)return LXMF_ERR_ARGUMENT;store_impl *s=store->implementation;char tmp[LXMF_STORE_PATH_MAX+5];if(strlen(s->path)+4>=sizeof tmp)return LXMF_ERR_BOUNDS;snprintf(tmp,sizeof tmp,"%s.tmp",s->path);FILE *out=fopen(tmp,"w+b");if(!out)return LXMF_ERR_CRYPTO;store_impl target={0};target.file=out;uint8_t content[LXMF_STORE_MAX_CONTENT];lxmf_status_t st=LXMF_OK;for(size_t i=0;i<s->count&&st==LXMF_OK;i++){lxmf_store_message_t m;st=lxmf_store_read(store,s->index[i].id,&m,content,sizeof content);if(st!=LXMF_OK)break;m.status=(lxmf_delivery_status_t)s->index[i].status;uint8_t payload[PUT_FIXED+LXMF_STORE_MAX_CONTENT];memcpy(payload,m.message_id,32);memcpy(payload+32,m.destination,16);memcpy(payload+48,m.source,16);uint64_t bits;memcpy(&bits,&m.timestamp,8);put64(payload+64,bits);payload[72]=(uint8_t)m.status;put32(payload+73,(uint32_t)m.content.len);memcpy(payload+PUT_FIXED,m.content.data,m.content.len);st=append_record(&target,TYPE_PUT,payload,(uint32_t)(PUT_FIXED+m.content.len),NULL);}if(st==LXMF_OK)st=sync_file(out);if(fclose(out)!=0&&st==LXMF_OK)st=LXMF_ERR_CRYPTO;if(st!=LXMF_OK){unlink(tmp);return st;}if(rename(tmp,s->path)!=0){unlink(tmp);return LXMF_ERR_CRYPTO;}fclose(s->file);s->file=fopen(s->path,"r+b");if(!s->file)return LXMF_ERR_CRYPTO;return scan(s);}
