#ifndef RETICULUM_RRC_SESSION_H
#define RETICULUM_RRC_SESSION_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include "reticulum/identity.h"
#include "reticulum/rrc.h"
#include "reticulum/runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

#define RNS_RRC_DEFAULT_MAX_NICK_BYTES 32u
#define RNS_RRC_DEFAULT_MAX_ROOM_BYTES 64u
#define RNS_RRC_DEFAULT_MAX_MESSAGE_BYTES 350u
#define RNS_RRC_DEFAULT_MAX_ROOMS 32u
#define RNS_RRC_DEFAULT_RATE_PER_MINUTE 240u
#define RNS_RRC_MAX_HUB_NAME_BYTES 255u
#define RNS_RRC_MAX_VERSION_BYTES 63u

typedef struct rns_rrc_session rns_rrc_session_t;

typedef enum rns_rrc_session_state {
    RNS_RRC_SESSION_DISCONNECTED = 0,
    RNS_RRC_SESSION_DISCOVERING,
    RNS_RRC_SESSION_LINKING,
    RNS_RRC_SESSION_HELLO,
    RNS_RRC_SESSION_CONNECTED,
    RNS_RRC_SESSION_RECONNECT_WAIT,
    RNS_RRC_SESSION_FAILED
} rns_rrc_session_state_t;

typedef struct rns_rrc_welcome {
    uint8_t hub_name[RNS_RRC_MAX_HUB_NAME_BYTES];
    size_t hub_name_length;
    uint8_t hub_version[RNS_RRC_MAX_VERSION_BYTES];
    size_t hub_version_length;
    bool resource_envelopes;
    size_t max_nick_bytes;
    size_t max_room_bytes;
    size_t max_message_bytes;
    size_t max_rooms;
    size_t rate_per_minute;
} rns_rrc_welcome_t;

typedef struct rns_rrc_session_info {
    rns_rrc_session_state_t state;
    rns_status_t last_error;
    size_t hello_attempts;
    size_t reconnect_attempts;
    uint64_t next_action_ms;
    rns_rrc_welcome_t welcome;
} rns_rrc_session_info_t;

typedef void (*rns_rrc_session_state_callback_t)(
    rns_rrc_session_t *session, const rns_rrc_session_info_t *info,
    void *context);
/* Envelope slices are immutable and callback-scoped. */
typedef void (*rns_rrc_session_envelope_callback_t)(
    rns_rrc_session_t *session, const rns_rrc_envelope_t *envelope,
    void *context);
/* Supplies Unix epoch milliseconds for envelope timestamps. The callback and
 * its context must remain valid for the session lifetime. */
typedef rns_status_t (*rns_rrc_session_wallclock_callback_t)(
    uint64_t *milliseconds, void *context);

typedef struct rns_rrc_session_options {
    rns_runtime_t *runtime;
    const rns_identity *local_identity;
    const rns_identity *hub_identity;
    uint8_t hub_destination[RNS_TRUNCATED_HASH_SIZE];
    const uint8_t *nick;
    size_t nick_length;
    bool auto_reconnect;
    uint64_t path_timeout_ms;
    uint64_t hello_interval_ms;
    size_t hello_max_attempts;
    double link_timeout_seconds;
    rns_rrc_session_state_callback_t state_callback;
    rns_rrc_session_envelope_callback_t envelope_callback;
    void *callback_context;
    rns_rrc_session_wallclock_callback_t wallclock_callback;
    void *wallclock_context;
} rns_rrc_session_options_t;

/* Parses a WELCOME body generated by the pinned NomadNet integer-keyed CBOR
 * schema. Unknown keys are ignored and omitted limits retain upstream
 * defaults. */
rns_status_t rns_rrc_welcome_parse(const uint8_t *body, size_t body_length,
                                   rns_rrc_welcome_t *welcome);

rns_status_t rns_rrc_session_create(rns_rrc_session_t **session,
                                    const rns_rrc_session_options_t *options);
void rns_rrc_session_destroy(rns_rrc_session_t *session);
rns_status_t rns_rrc_session_connect(rns_rrc_session_t *session,
                                     uint64_t now_ms);
rns_status_t rns_rrc_session_poll(rns_rrc_session_t *session,
                                  uint64_t now_ms);
void rns_rrc_session_disconnect(rns_rrc_session_t *session);
void rns_rrc_session_get_info(const rns_rrc_session_t *session,
                              rns_rrc_session_info_t *info);

rns_status_t rns_rrc_session_join(rns_rrc_session_t *session,
                                  const uint8_t *room, size_t room_length,
                                  const uint8_t *key, size_t key_length);
rns_status_t rns_rrc_session_part(rns_rrc_session_t *session,
                                  const uint8_t *room, size_t room_length);
rns_status_t rns_rrc_session_send_message(rns_rrc_session_t *session,
                                          const uint8_t *room,
                                          size_t room_length,
                                          const uint8_t *message,
                                          size_t message_length,
                                          uint8_t message_id[8]);
rns_status_t rns_rrc_session_ping(rns_rrc_session_t *session,
                                  uint8_t nonce[8]);

#ifdef __cplusplus
}
#endif
#endif
