[reticulum]
  enable_transport = No
  share_instance = No
  panic_on_interface_error = No
  shared_instance_port = 37428
  instance_control_port = 37429

[interfaces]
  [[ReticulumNet Netherlands]]
    type = TCPClientInterface
    enabled = Yes
    target_host = node.reticulumnet.nl
    target_port = 4242

  [[RMAP World]]
    type = TCPClientInterface
    enabled = Yes
    target_host = rmap.world
    target_port = 4242
