/* Generated by tools/generate_lxmf_announce_fixtures.py.
 * Reticulum commit: ea98db4f53dcf0defc0e71a16e60d28b1229c4e6
 * LXMF commit: 795fdaa2b0777c13033787d933d1afc94a2377cb
 * Source API: LXMF.LXMRouter.LXMRouter.get_announce_app_data
 * Do not edit manually. */
#ifndef RETICULUM_TEST_LXMF_ANNOUNCE_FIXTURES_H
#define RETICULUM_TEST_LXMF_ANNOUNCE_FIXTURES_H
#include <stddef.h>
#include <stdint.h>
typedef struct {
    const uint8_t *name; size_t name_len; int stamp_cost;
    const uint8_t *wire; size_t wire_len;
} lxmf_python_announce_fixture;
static const uint8_t fixture_name_0[] = {0x52, 0x65, 0x69};
static const uint8_t fixture_wire_0[] = {0x93, 0xc4, 0x03, 0x52, 0x65, 0x69, 0x08, 0x91, 0x00};
static const uint8_t fixture_name_1[] = {0x4e, 0x6f, 0x6d, 0x61, 0x64, 0x20, 0x4e, 0x6f, 0x64, 0x65, 0x20, 0xf0, 0x9f, 0x8c, 0xb8};
static const uint8_t fixture_wire_1[] = {0x93, 0xc4, 0x0f, 0x4e, 0x6f, 0x6d, 0x61, 0x64, 0x20, 0x4e, 0x6f, 0x64, 0x65, 0x20, 0xf0, 0x9f, 0x8c, 0xb8, 0xc0, 0x91, 0x00};
static const uint8_t fixture_wire_2[] = {0x93, 0xc4, 0x00, 0xcc, 0xfe, 0x91, 0x00};
static const lxmf_python_announce_fixture lxmf_python_announce_fixtures[] = {
    {fixture_name_0, 3u, 8, fixture_wire_0, 9u},
    {fixture_name_1, 15u, -1, fixture_wire_1, 21u},
    {NULL, 0u, 254, fixture_wire_2, 7u},
};
#define LXMF_PYTHON_ANNOUNCE_FIXTURE_COUNT \
    (sizeof lxmf_python_announce_fixtures / sizeof lxmf_python_announce_fixtures[0])
#endif
