#include "reticulum/node_registry.h"
#include <string.h>
#include <stdio.h>
#include "reticulum/destination.h"
#define REGISTRY_MAGIC "RNSN1\0\0\0"

void rns_node_registry_init(rns_node_registry *r, double lifetime) { if (r) { memset(r, 0, sizeof(*r)); r->lifetime = lifetime > 0 ? lifetime : 3600.0; } }
int rns_node_registry_upsert(rns_node_registry *r, const rns_node_record *x) {
    if (!r || !x) return 0; size_t i; for (i=0;i<r->count;i++) if (!memcmp(r->records[i].destination,x->destination,16)) break;
    if (i==r->count) { if (r->count==RNS_NODE_REGISTRY_MAX) return 0; r->count++; }
    r->records[i]=*x; if (r->records[i].expires_at <= 0.0) r->records[i].expires_at=r->records[i].seen_at+r->lifetime; r->records[i].name[sizeof(r->records[i].name)-1]=0; return 1;
}
size_t rns_node_registry_expire(rns_node_registry *r, double now) { if (!r) return 0; size_t n=0; for(size_t i=0;i<r->count;) { if(r->records[i].expires_at>0&&r->records[i].expires_at<=now){r->records[i]=r->records[--r->count];n++;} else i++; } return n; }
const rns_node_record *rns_node_registry_get(const rns_node_registry *r,const uint8_t d[16]) { if(!r||!d)return NULL; for(size_t i=0;i<r->count;i++)if(!memcmp(r->records[i].destination,d,16))return &r->records[i]; return NULL; }
size_t rns_node_registry_list(const rns_node_registry *r,rns_node_record *out,size_t cap,const char *filter){if(!r)return 0;size_t n=0;for(size_t i=0;i<r->count&&n<cap;i++){if(filter&&*filter&&!strstr(r->records[i].name,filter))continue;if(out)out[n]=r->records[i];n++;}return n;}
int rns_node_registry_consider_announce(rns_node_registry *r,const rns_node_result *a){if(!r||!a||!a->has_verified_announce||a->announce_app_data_length>RNS_NODE_APP_DATA_MAX)return 0;const rns_node_record *old=rns_node_registry_get(r,a->destination_hash);if(old&&old->announce_timebase>=a->announce_timebase)return 0;rns_node_record n={0};memcpy(n.destination,a->destination_hash,16);memcpy(n.next_hop,a->next_hop,16);rns_identity_export_public(&a->announce_identity,n.public_key);if(a->announce_app_data_length)memcpy(n.app_data,a->announce_app_data,a->announce_app_data_length);n.app_data_length=a->announce_app_data_length;n.announce_timebase=a->announce_timebase;n.hops=a->hops;n.interface_id=a->received_interface_id;n.seen_at=a->received_at;n.expires_at=a->received_at+r->lifetime;n.reachable=true;n.has_ratchet=a->announce_has_ratchet!=0;const char *node_aspects[]={"node"};const char *delivery_aspects[]={"delivery"};uint8_t node_hash[16],delivery_hash[16];if(rns_destination_hash(&a->announce_identity,"nomadnetwork",node_aspects,1,node_hash)&&!memcmp(node_hash,a->destination_hash,16)){n.kind=RNS_NODE_KIND_NOMAD;if(rns_destination_hash(&a->announce_identity,"lxmf",delivery_aspects,1,delivery_hash)){memcpy(n.message_destination,delivery_hash,16);n.has_message_destination=true;}size_t name_length=a->announce_app_data_length<sizeof(n.name)-1?a->announce_app_data_length:sizeof(n.name)-1;for(size_t i=0;i<name_length;i++){unsigned char c=a->announce_app_data[i];n.name[i]=c>=32u&&c!=127u?(char)c:'?';}}else if(rns_destination_hash(&a->announce_identity,"lxmf",delivery_aspects,1,delivery_hash)&&!memcmp(delivery_hash,a->destination_hash,16)){n.kind=RNS_NODE_KIND_LXMF;memcpy(n.message_destination,a->destination_hash,16);n.has_message_destination=true;}return rns_node_registry_upsert(r,&n);}
static int before(const rns_node_record *a,const rns_node_record *b){if(a->reachable!=b->reachable)return a->reachable;if(a->seen_at!=b->seen_at)return a->seen_at>b->seen_at;return memcmp(a->destination,b->destination,16)<0;}
size_t rns_node_registry_sorted(const rns_node_registry *r,rns_node_record *out,size_t cap){size_t n=rns_node_registry_list(r,out,cap,NULL);for(size_t i=1;i<n;i++){rns_node_record x=out[i];size_t j=i;while(j&&before(&x,&out[j-1])){out[j]=out[j-1];j--;}out[j]=x;}return n;}
int rns_node_registry_save(const rns_node_registry *r,const char *path){if(!r||!path)return 0;FILE *f=fopen(path,"wb");if(!f)return 0;uint32_t n=(uint32_t)r->count;int ok=fwrite(REGISTRY_MAGIC,1,8,f)==8&&fwrite(&n,sizeof n,1,f)==1&&fwrite(r->records,sizeof(r->records[0]),r->count,f)==r->count&&fflush(f)==0;if(fclose(f)!=0)ok=0;return ok;}
int rns_node_registry_load(rns_node_registry *r,const char *path,double lifetime){if(!r||!path)return 0;FILE *f=fopen(path,"rb");if(!f)return 0;char magic[8];uint32_t n=0;int ok=fread(magic,1,8,f)==8&&!memcmp(magic,REGISTRY_MAGIC,8)&&fread(&n,sizeof n,1,f)==1&&n<=RNS_NODE_REGISTRY_MAX;if(ok){rns_node_registry_init(r,lifetime);ok=fread(r->records,sizeof(r->records[0]),n,f)==n&&fgetc(f)==EOF;if(ok)r->count=n;}fclose(f);return ok;}
