#!/usr/bin/env python3
"""Generate signed LXMF message vectors with the pinned upstream APIs."""

import argparse
import hashlib
import pathlib
import subprocess
import sys
from types import SimpleNamespace

RNS_COMMIT = "ea98db4f53dcf0defc0e71a16e60d28b1229c4e6"
LXMF_COMMIT = "795fdaa2b0777c13033787d933d1afc94a2377cb"


def checked_head(repository: pathlib.Path, expected: str) -> None:
    actual = subprocess.check_output(
        ["git", "-C", str(repository), "rev-parse", "HEAD"], text=True
    ).strip()
    if actual != expected:
        raise SystemExit(f"{repository}: expected commit {expected}, found {actual}")


def c_bytes(data: bytes) -> str:
    return ", ".join(f"0x{value:02x}" for value in data)


def byte_array(lines: list[str], name: str, data: bytes) -> str:
    if not data:
        return "NULL"
    lines.append(f"static const uint8_t {name}[] = {{{c_bytes(data)}}};")
    return name


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reticulum", required=True, type=pathlib.Path)
    parser.add_argument("--lxmf", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()
    checked_head(args.reticulum, RNS_COMMIT)
    checked_head(args.lxmf, LXMF_COMMIT)
    sys.path.insert(0, str(args.lxmf))
    sys.path.insert(0, str(args.reticulum))

    import LXMF  # pylint: disable=import-outside-toplevel
    import RNS  # pylint: disable=import-outside-toplevel
    import RNS.vendor.umsgpack as msgpack  # pylint: disable=import-outside-toplevel
    from LXMF.LXMessage import LXMessage  # pylint: disable=import-outside-toplevel
    from LXMF.LXMF import (  # pylint: disable=import-outside-toplevel
        FIELD_REACTION,
        FIELD_RENDERER,
        FIELD_REPLY_TO,
    )

    if not pathlib.Path(LXMF.__file__).resolve().is_relative_to(args.lxmf.resolve()):
        raise SystemExit("imported LXMF from outside the pinned checkout")
    if not pathlib.Path(RNS.__file__).resolve().is_relative_to(args.reticulum.resolve()):
        raise SystemExit("imported RNS from outside the pinned checkout")

    # Destination construction normally registers with a running Reticulum
    # instance. The fixture needs no interfaces, so provide only the owner flag
    # that the authoritative constructor consults.
    RNS.Transport.owner = SimpleNamespace(is_connected_to_shared_instance=False)
    source_identity = RNS.Identity.from_bytes(bytes(range(1, 65)))
    destination_identity = RNS.Identity.from_bytes(bytes(range(65, 129)))
    source = RNS.Destination(
        source_identity, RNS.Destination.IN, RNS.Destination.SINGLE,
        "lxmf", "delivery"
    )
    destination = RNS.Destination(
        destination_identity, RNS.Destination.OUT, RNS.Destination.SINGLE,
        "lxmf", "delivery"
    )

    cases = [
        {
            "timestamp": 1700000000.25,
            "title": "Topic π",
            "content": "Hello 🌸",
            "fields": {
                FIELD_RENDERER: 1,
                FIELD_REPLY_TO: bytes(range(32)),
                FIELD_REACTION: {0: b"like"},
                0x123: b"future",
            },
        },
        {"timestamp": 1.5, "title": "", "content": "", "fields": {}},
        {"timestamp": 1.5, "title": "", "content": b"A" * 255, "fields": {}},
    ]
    vectors = []
    for case in cases:
        message = LXMessage(
            destination, source, case["content"], case["title"],
            fields=case["fields"], desired_method=LXMessage.OPPORTUNISTIC
        )
        message.timestamp = case["timestamp"]
        message.pack()
        packet = message._LXMessage__as_packet()
        if message.method != LXMessage.OPPORTUNISTIC or message.representation != LXMessage.PACKET:
            raise SystemExit("fixture case is not a valid opportunistic packet")
        if packet.data != message.packed[LXMessage.DESTINATION_LENGTH:]:
            raise SystemExit("unexpected opportunistic application payload layout")
        payload = msgpack.packb(message.payload[:4])
        preimage = destination.hash + source.hash + payload + message.message_id
        vectors.append({
            "destination": destination.hash,
            "source": source.hash,
            "source_public": source_identity.get_public_key(),
            "timestamp": case["timestamp"],
            "title": message.title,
            "content": message.content,
            "fields": msgpack.packb(message.fields),
            "message_id": message.message_id,
            "signature": message.signature,
            "preimage_sha256": hashlib.sha256(preimage).digest(),
            "packed": message.packed,
            "opportunistic_payload": packet.data,
        })

    lines = [
        "/* Generated by tools/generate_lxmf_message_fixtures.py.",
        f" * Reticulum commit: {RNS_COMMIT}",
        f" * LXMF commit: {LXMF_COMMIT}",
        " * Source APIs: LXMF.LXMessage.pack and LXMF.LXMessage.__as_packet",
        " * Contains public test material only. Do not edit manually. */",
        "#ifndef RETICULUM_TEST_LXMF_MESSAGE_FIXTURES_H",
        "#define RETICULUM_TEST_LXMF_MESSAGE_FIXTURES_H",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "typedef struct {",
        "    const uint8_t *destination; const uint8_t *source;",
        "    const uint8_t *source_public; double timestamp;",
        "    const uint8_t *title; size_t title_len;",
        "    const uint8_t *content; size_t content_len;",
        "    const uint8_t *fields; size_t fields_len;",
        "    const uint8_t *message_id; const uint8_t *signature;",
        "    const uint8_t *preimage_sha256;",
        "    const uint8_t *packed; size_t packed_len;",
        "    const uint8_t *opportunistic_payload; size_t opportunistic_payload_len;",
        "} lxmf_python_message_fixture;",
    ]
    references = []
    for index, vector in enumerate(vectors):
        refs = {}
        for key in (
            "destination", "source", "source_public", "title", "content",
            "fields", "message_id", "signature", "preimage_sha256", "packed",
            "opportunistic_payload"
        ):
            refs[key] = byte_array(lines, f"message_fixture_{index}_{key}", vector[key])
        references.append(refs)
    lines.append("static const lxmf_python_message_fixture lxmf_python_message_fixtures[] = {")
    for vector, refs in zip(vectors, references):
        lines.extend([
            "    {",
            f"        {refs['destination']}, {refs['source']}, {refs['source_public']}, {vector['timestamp']!r},",
            f"        {refs['title']}, {len(vector['title'])}u, {refs['content']}, {len(vector['content'])}u,",
            f"        {refs['fields']}, {len(vector['fields'])}u, {refs['message_id']}, {refs['signature']},",
            f"        {refs['preimage_sha256']}, {refs['packed']}, {len(vector['packed'])}u,",
            f"        {refs['opportunistic_payload']}, {len(vector['opportunistic_payload'])}u",
            "    },",
        ])
    lines.extend([
        "};",
        "#define LXMF_PYTHON_MESSAGE_FIXTURE_COUNT \\",
        "    (sizeof lxmf_python_message_fixtures / sizeof lxmf_python_message_fixtures[0])",
        "#endif",
        "",
    ])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
