#!/usr/bin/env python3
"""Generate delivery-announce vectors with the pinned upstream Python code."""

import argparse
import pathlib
import subprocess
import sys
from types import SimpleNamespace

RNS_COMMIT = "ea98db4f53dcf0defc0e71a16e60d28b1229c4e6"
LXMF_COMMIT = "795fdaa2b0777c13033787d933d1afc94a2377cb"


def checked_head(repository: pathlib.Path, expected: str) -> None:
    actual = subprocess.check_output(
        ["git", "-C", str(repository), "rev-parse", "HEAD"], text=True
    ).strip()
    if actual != expected:
        raise SystemExit(
            f"{repository}: expected commit {expected}, found {actual}"
        )


def c_bytes(data: bytes) -> str:
    return ", ".join(f"0x{value:02x}" for value in data)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--reticulum", required=True, type=pathlib.Path)
    parser.add_argument("--lxmf", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()

    checked_head(args.reticulum, RNS_COMMIT)
    checked_head(args.lxmf, LXMF_COMMIT)
    sys.path.insert(0, str(args.lxmf))
    sys.path.insert(0, str(args.reticulum))

    import LXMF  # pylint: disable=import-outside-toplevel
    import RNS  # pylint: disable=import-outside-toplevel
    from LXMF.LXMF import SF_COMPRESSION  # pylint: disable=import-outside-toplevel
    from LXMF.LXMRouter import LXMRouter  # pylint: disable=import-outside-toplevel

    if not pathlib.Path(LXMF.__file__).resolve().is_relative_to(args.lxmf.resolve()):
        raise SystemExit("imported LXMF from outside the pinned checkout")
    if not pathlib.Path(RNS.__file__).resolve().is_relative_to(args.reticulum.resolve()):
        raise SystemExit("imported RNS from outside the pinned checkout")
    if SF_COMPRESSION != 0:
        raise SystemExit(f"unexpected SF_COMPRESSION value {SF_COMPRESSION}")

    cases = [("Rei", 8), ("Nomad Node 🌸", None), ("", 254)]
    vectors = []
    for index, (name, stamp_cost) in enumerate(cases, 1):
        destination_hash = bytes([index]) * 16
        destination = SimpleNamespace(display_name=name, stamp_cost=stamp_cost)
        router = SimpleNamespace(delivery_destinations={destination_hash: destination})
        wire = LXMRouter.get_announce_app_data(router, destination_hash)
        vectors.append((name.encode("utf-8"), stamp_cost, wire))

    lines = [
        "/* Generated by tools/generate_lxmf_announce_fixtures.py.",
        f" * Reticulum commit: {RNS_COMMIT}",
        f" * LXMF commit: {LXMF_COMMIT}",
        " * Source API: LXMF.LXMRouter.LXMRouter.get_announce_app_data",
        " * Do not edit manually. */",
        "#ifndef RETICULUM_TEST_LXMF_ANNOUNCE_FIXTURES_H",
        "#define RETICULUM_TEST_LXMF_ANNOUNCE_FIXTURES_H",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "typedef struct {",
        "    const uint8_t *name; size_t name_len; int stamp_cost;",
        "    const uint8_t *wire; size_t wire_len;",
        "} lxmf_python_announce_fixture;",
    ]
    for index, (name, _stamp_cost, wire) in enumerate(vectors):
        if name:
            lines.append(f"static const uint8_t fixture_name_{index}[] = {{{c_bytes(name)}}};")
        lines.append(f"static const uint8_t fixture_wire_{index}[] = {{{c_bytes(wire)}}};")
    lines.append("static const lxmf_python_announce_fixture lxmf_python_announce_fixtures[] = {")
    for index, (name, stamp_cost, wire) in enumerate(vectors):
        cost = -1 if stamp_cost is None else stamp_cost
        name_expr = f"fixture_name_{index}" if name else "NULL"
        lines.append(
            f"    {{{name_expr}, {len(name)}u, {cost}, fixture_wire_{index}, {len(wire)}u}},"
        )
    lines.extend([
        "};",
        "#define LXMF_PYTHON_ANNOUNCE_FIXTURE_COUNT \\",
        "    (sizeof lxmf_python_announce_fixtures / sizeof lxmf_python_announce_fixtures[0])",
        "#endif",
        "",
    ])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
