#!/usr/bin/env python3
"""Generate bounded standard-field vectors from pinned LXMF 1.1.0 constants."""

import argparse
import datetime
import hashlib
import importlib.util
import json
from pathlib import Path
import subprocess
import sys

LXMF_COMMIT = "795fdaa2b0777c13033787d933d1afc94a2377cb"
RNS_COMMIT = "ea98db4f53dcf0defc0e71a16e60d28b1229c4e6"


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def checked_revision(root):
    actual = subprocess.check_output(
        ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
    ).strip()
    if actual != LXMF_COMMIT:
        raise RuntimeError("LXMF revision mismatch")
    dirty = subprocess.check_output(
        ["git", "-C", str(root), "status", "--porcelain", "--untracked-files=no"],
        text=True,
    ).strip()
    if dirty:
        raise RuntimeError("LXMF checkout has tracked modifications")


def checked_rns_source(root):
    if (root / ".git").exists():
        actual = subprocess.check_output(
            ["git", "-C", str(root), "rev-parse", "HEAD"], text=True
        ).strip()
        dirty = subprocess.check_output(
            ["git", "-C", str(root), "status", "--porcelain", "--untracked-files=no"],
            text=True,
        ).strip()
        if actual != RNS_COMMIT or dirty:
            raise RuntimeError("RNS checkout revision or status mismatch")
        return
    marker = root.parent / f"{root.name}.provenance"
    if not marker.is_file():
        raise RuntimeError("missing RNS source provenance")
    fields = dict(
        line.split("=", 1) for line in marker.read_text().splitlines() if "=" in line
    )
    if fields.get("commit") != RNS_COMMIT or fields.get("tracked_status") != "clean":
        raise RuntimeError("RNS source provenance mismatch")


def c_array(name, data):
    values = ", ".join(f"0x{byte:02x}u" for byte in data)
    return f"static const uint8_t {name}[] = {{\n    {values}\n}};\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--lxmf", required=True, type=Path)
    parser.add_argument("--rns", required=True, type=Path)
    parser.add_argument("--header", required=True, type=Path)
    parser.add_argument("--provenance", required=True, type=Path)
    args = parser.parse_args()
    checked_revision(args.lxmf)
    checked_rns_source(args.rns)
    sys.path.insert(0, str(args.rns.resolve()))
    import RNS.vendor.umsgpack as msgpack  # pylint: disable=import-outside-toplevel

    constants = load("pinned_lxmf_constants", args.lxmf / "LXMF" / "LXMF.py")
    reply = bytes(range(32))
    reaction = bytes(reversed(range(32)))
    thread = bytes(range(0x80, 0xa0))
    fields = {
        constants.FIELD_RENDERER: constants.RENDERER_MARKDOWN,
        constants.FIELD_REPLY_TO: reply,
        constants.FIELD_REPLY_QUOTE: "quoted 🌸".encode(),
        constants.FIELD_REACTION: {
            constants.REACTION_TO: reaction,
            constants.REACTION_CONTENT: "👍".encode(),
        },
        constants.FIELD_THREAD: thread,
        constants.FIELD_FILE_ATTACHMENTS: [
            ["notes.txt", b"\x00\x01"],
            ["data.bin", b"\xff\xfe\xfd"],
        ],
        constants.FIELD_IMAGE: ["png", b"\x89PNG\r\n\x1a\n"],
        constants.FIELD_AUDIO: [constants.AM_OPUS_OGG, b"OggS\x00\x02"],
    }
    packed = msgpack.packb(fields)
    header = (
        "/* Generated by tools/generate_lxmf_standard_fields_fixture.py.\n"
        f" * Pinned LXMF commit: {LXMF_COMMIT}. */\n"
        "#ifndef LXMF_STANDARD_FIELDS_FIXTURE_H\n"
        "#define LXMF_STANDARD_FIELDS_FIXTURE_H\n"
        "#include <stdint.h>\n"
        + c_array("lxmf_standard_fields_fixture", packed)
        + "#endif\n"
    )
    args.header.write_text(header)
    report = {
        "schema": 1,
        "lxmf_commit": LXMF_COMMIT,
        "rns_commit": RNS_COMMIT,
        "generated_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "generator": "tools/generate_lxmf_standard_fields_fixture.py",
        "source_constants": "LXMF/LXMF.py",
        "encoder": "RNS.vendor.umsgpack.packb",
        "fixture_sha256": hashlib.sha256(packed).hexdigest(),
        "fixture_size": len(packed),
        "evidence": "deterministic fixture equality; not live interoperability",
    }
    args.provenance.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")


if __name__ == "__main__":
    main()
