#!/usr/bin/env python3
"""Generate URI vectors through pinned LXMessage.as_uri without identities."""
import argparse
import hashlib
import json
import pathlib
import subprocess
import sys
from types import SimpleNamespace

LXMF_COMMIT = "795fdaa2b0777c13033787d933d1afc94a2377cb"
RNS_COMMIT = "ea98db4f53dcf0defc0e71a16e60d28b1229c4e6"

def head(path):
    return subprocess.check_output(
        ["git", "-C", str(path), "rev-parse", "HEAD"], text=True).strip()

def array(name, data):
    body = ",".join(f"0x{byte:02x}" for byte in data)
    return f"static const uint8_t {name}[] = {{{body}}};\n"

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--lxmf", required=True, type=pathlib.Path)
    parser.add_argument("--reticulum", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    args = parser.parse_args()
    if head(args.lxmf) != LXMF_COMMIT:
        raise SystemExit("LXMF checkout is not the pinned revision")
    if head(args.reticulum) != RNS_COMMIT:
        raise SystemExit("Reticulum checkout is not the pinned revision")
    sys.path[:0] = [str(args.reticulum), str(args.lxmf)]
    from LXMF.LXMessage import LXMessage
    cases = [
        ("small", bytes(range(1, 98))),
        ("binary", bytes((i * 197 + 31) & 255 for i in range(2048))),
        ("maximum", bytes((i * 73 + i // 9) & 255 for i in range(2210))),
    ]
    lines = [
        "/* Generated by tools/generate_lxmf_paper_fixtures.py from pinned",
        f" * LXMF {LXMF_COMMIT} with Reticulum {RNS_COMMIT};",
        " * LXMessage.as_uri(finalise=False). No identity or key material. */",
        "#ifndef LXMF_PAPER_VECTORS_H", "#define LXMF_PAPER_VECTORS_H",
        "#include <stddef.h>", "#include <stdint.h>",
        "typedef struct { const uint8_t *paper; size_t paper_len;",
        " const char *uri; size_t uri_len; uint8_t transient[32]; } paper_fixture;",
    ]
    rows = []
    for name, paper in cases:
        fake = SimpleNamespace(packed=b"present", desired_method=LXMessage.PAPER,
                               paper_packed=paper)
        uri = LXMessage.as_uri(fake, finalise=False)
        lines.append(array(f"paper_{name}", paper))
        rows.append((name, uri))
    lines.append("static const paper_fixture paper_fixtures[] = {")
    for name, uri in rows:
        lines.append(f' {{paper_{name},sizeof paper_{name},"{uri}",'
                     f'{len(uri)},{{' + ",".join(f"0x{x:02x}" for x in
                     hashlib.sha256(dict(cases)[name]).digest()) + "}},")
    lines += ["};", "#endif"]
    args.output.write_text("\n".join(lines) + "\n")
    provenance = {
        "schema": 1,
        "producer": "LXMF.LXMessage.as_uri(finalise=False)",
        "reticulum_commit": RNS_COMMIT,
        "lxmf_commit": LXMF_COMMIT,
        "lxmessage_sha256": hashlib.sha256(
            (args.lxmf / "LXMF/LXMessage.py").read_bytes()).hexdigest(),
        "fixture_sha256": hashlib.sha256(args.output.read_bytes()).hexdigest(),
        "cases": [{"name": name, "paper_bytes": len(paper)}
                  for name, paper in cases],
        "contains_private_material": False,
    }
    args.output.with_suffix(".provenance.json").write_text(
        json.dumps(provenance, indent=2, sort_keys=True) + "\n")

if __name__ == "__main__":
    main()
