#include "reticulum/embedded_link.h"
#include "reticulum/packet.h"
#include <assert.h>
#include <stdbool.h>
#include <string.h>
typedef struct {uint8_t data[500];size_t length;uint32_t id;} frame;
typedef struct {frame frames[64];size_t count;uint32_t sequence;unsigned data,proof,complete;bool reject,reject_enqueue;} endpoint;
static rns_status_t start(void *ctx){(void)ctx;return RNS_OK;}
static void stop(void *ctx){(void)ctx;}
static rns_status_t stats(void *ctx,rns_interface_stats_t *out){(void)ctx;memset(out,0,sizeof *out);return RNS_OK;}
static rns_status_t poll_interface(void *ctx,rns_interface_receive_fn fn,void *user,size_t budget){(void)ctx;(void)fn;(void)user;(void)budget;return RNS_OK;}
static rns_status_t untracked(void *ctx,const uint8_t *data,size_t length){(void)ctx;(void)data;(void)length;return RNS_ERROR_UNSUPPORTED;}
static rns_status_t enqueue(void *ctx,const uint8_t *data,size_t length,uint32_t *id) {
    endpoint *e=ctx;if(e->reject_enqueue)return RNS_ERROR_IO;if(e->count==64)return RNS_ERROR_OVERFLOW;
    frame *f=&e->frames[e->count++];memcpy(f->data,data,length);f->length=length;f->id=++e->sequence;*id=f->id;return RNS_OK;
}
static rns_status_t data(void *ctx,const uint8_t id[16],const uint8_t *bytes,size_t length) {
    endpoint *e=ctx;(void)id;assert(length==2&&memcmp(bytes,"hi",2)==0);e->data++;return e->reject?RNS_ERROR_IO:RNS_OK;
}
static void proof(void *ctx,const uint8_t id[16],const uint8_t hash[32]){(void)id;(void)hash;((endpoint *)ctx)->proof++;}
static void complete(void *ctx,const uint8_t id[16],const uint8_t hash[32],rns_status_t status){(void)id;(void)hash;if(status==RNS_OK)((endpoint *)ctx)->complete++;}
static frame pop(endpoint *e){assert(e->count);frame f=e->frames[0];memmove(e->frames,e->frames+1,(--e->count)*sizeof(frame));return f;}
static void transfer(endpoint *e,rns_embedded_link_manager *from,rns_embedded_link_manager *to,uint64_t now) {
    frame f=pop(e);rns_embedded_link_tx_complete(from,f.id,RNS_OK,now);
    assert(rns_embedded_link_receive(to,f.data,f.length,now+1)==RNS_OK);
}
int main(void) {
    endpoint a={0},b={0};rns_identity ia,ib;assert(rns_identity_generate(&ia)&&rns_identity_generate(&ib));
    uint8_t da[16]={1},db[16]={2},id[16],hash[32];
    rns_interface_ops_t ops={.start=start,.stop=stop,.send=untracked,.poll=poll_interface,.get_stats=stats,.send_with_id=enqueue};rns_interface_t *ifa,*ifb;
    assert(rns_interface_create(&ops,&a,&ifa)==RNS_OK);assert(rns_interface_create(&ops,&b,&ifb)==RNS_OK);
    assert(rns_interface_start(ifa)==RNS_OK&&rns_interface_start(ifb)==RNS_OK);
    rns_embedded_link_callbacks cb={.data=data,.proof=proof,.transmission=complete};
    rns_embedded_link_manager *ma,*mb;
    assert(rns_embedded_link_create(&ia,da,ifa,&cb,&a,&ma)==RNS_OK);
    assert(rns_embedded_link_create(&ib,db,ifb,&cb,&b,&mb)==RNS_OK);
    assert(rns_embedded_link_connect(ma,db,&ib,0,id)==RNS_OK);
    rns_embedded_link_poll(ma,130000);rns_link_state state;
    assert(rns_embedded_link_state(ma,id,&state)==RNS_OK&&state==RNS_LINK_PENDING);
    frame request=a.frames[0];
    frame ifac=request;ifac.data[0]|=0x80u;
    assert(rns_embedded_link_receive(mb,ifac.data,ifac.length,130000)==RNS_ERROR_PROTOCOL);
    transfer(&a,ma,mb,130001);assert(b.count==1);
    assert(rns_embedded_link_receive(mb,request.data,request.length,130002)==RNS_OK&&b.count==1);
    frame corrupt=b.frames[0];corrupt.data[corrupt.length-10]^=1;
    assert(rns_embedded_link_receive(ma,corrupt.data,corrupt.length,130003)==RNS_ERROR_CRYPTO);
    /* A lost proof can be regenerated by a repeated request, without a slot. */
    frame lost=pop(&b);rns_embedded_link_tx_complete(mb,lost.id,RNS_OK,130004);
    assert(rns_embedded_link_receive(mb,request.data,request.length,130005)==RNS_OK&&b.count==1);
    transfer(&b,mb,ma,130010);transfer(&a,ma,mb,130020);
    assert(rns_embedded_link_state(ma,id,&state)==RNS_OK&&state==RNS_LINK_HANDSHAKE);
    assert(rns_embedded_link_send(ma,id,(const uint8_t *)"hi",2,130022,hash)==RNS_ERROR_INVALID_STATE);
    transfer(&a,ma,mb,130030);
    rns_identity peer;assert(rns_embedded_link_authenticated_peer(mb,id,&peer)==RNS_OK);
    assert(memcmp(peer.hash,ia.hash,16)==0&&!peer.has_private);
    assert(rns_embedded_link_authenticated_peer(ma,id,&peer)==RNS_OK&&!peer.has_private);
    assert(rns_embedded_link_send(ma,id,(const uint8_t *)"hi",2,130040,hash)==RNS_OK);
    transfer(&a,ma,mb,130050);transfer(&b,mb,ma,130060);
    assert(a.complete==1&&a.proof==1&&b.data==1);
    assert(rns_embedded_link_send(mb,id,(const uint8_t *)"hi",2,130070,hash)==RNS_OK);
    transfer(&b,mb,ma,130080);transfer(&a,ma,mb,130090);assert(b.proof==1);
    /* Valid implicit proof before completion notification must wait for RF. */
    assert(rns_embedded_link_send(ma,id,(const uint8_t *)"hi",2,130091,hash)==RNS_OK);
    frame early=pop(&a);
    assert(rns_embedded_link_receive(mb,early.data,early.length,130092)==RNS_OK);
    frame explicit=pop(&b);rns_packet parsed;assert(rns_packet_decode(&parsed,explicit.data,explicit.length));
    uint8_t implicit[500];size_t implicit_length;
    parsed.data+=32;parsed.data_length-=32;assert(rns_packet_encode(&parsed,implicit,sizeof implicit,&implicit_length));
    assert(rns_embedded_link_receive(ma,implicit,implicit_length,130093)==RNS_OK&&a.proof==1);
    rns_embedded_link_tx_complete(ma,early.id,RNS_OK,130094);assert(a.proof==2&&a.complete==2);
    rns_embedded_link_tx_complete(mb,explicit.id,RNS_OK,130095);
    /* Resource frames are explicitly unsupported, never acknowledged. */
    parsed.packet_type=0;parsed.context=2;parsed.data=(const uint8_t *)"x";parsed.data_length=1;
    assert(rns_packet_encode(&parsed,implicit,sizeof implicit,&implicit_length));
    assert(rns_embedded_link_receive(ma,implicit,implicit_length,130096)==RNS_ERROR_UNSUPPORTED);
    rns_embedded_link_poll(ma,490100);assert(a.count==1);
    rns_packet keep;assert(rns_packet_decode(&keep,a.frames[0].data,a.frames[0].length));
    assert(keep.context==0xfa&&keep.data_length==1&&keep.data[0]==0xff);
    transfer(&a,ma,mb,490101);transfer(&b,mb,ma,490103);
    b.reject=true;assert(rns_embedded_link_send(ma,id,(const uint8_t *)"hi",2,500100,hash)==RNS_OK);
    /* Queue delay also suspends idle expiry, but never the bounded queue cap. */
    rns_embedded_link_poll(ma,1000100);assert(rns_embedded_link_state(ma,id,&state)==RNS_OK);
    frame f=pop(&a);rns_embedded_link_tx_complete(ma,f.id,RNS_OK,1000110);
    rns_embedded_link_poll(ma,1000111);assert(rns_embedded_link_state(ma,id,&state)==RNS_OK);
    assert(rns_embedded_link_receive(mb,f.data,f.length,1000111)==RNS_ERROR_IO);assert(b.count==0);
    rns_embedded_link_poll(ma,1120111);assert(rns_embedded_link_state(ma,id,&state)==RNS_ERROR_NOT_FOUND);
    rns_embedded_link_destroy(ma);rns_embedded_link_destroy(mb);
    memset(&a,0,sizeof a);memset(&b,0,sizeof b);
    assert(rns_embedded_link_create(&ia,da,ifa,&cb,&a,&ma)==RNS_OK);
    assert(rns_embedded_link_create(&ib,db,ifb,&cb,&b,&mb)==RNS_OK);
    /* Four slots maximum and stalled queued frames are eventually reclaimed. */
    for(unsigned i=0;i<4;i++){db[0]=(uint8_t)(i+2);assert(rns_embedded_link_connect(ma,db,&ib,0,id)==RNS_OK);}
    db[0]=9;assert(rns_embedded_link_connect(ma,db,&ib,0,id)==RNS_ERROR_OVERFLOW);
    rns_embedded_link_poll(ma,3600001);assert(rns_embedded_link_connect(ma,db,&ib,3600002,id)==RNS_OK);
    frame failure=pop(&a);(void)failure;
    rns_embedded_link_tx_complete(ma,a.frames[a.count-1].id,RNS_ERROR_IO,3600003);
    assert(rns_embedded_link_state(ma,id,&state)==RNS_ERROR_NOT_FOUND);
    a.count=0;b.count=0;db[0]=2;
    assert(rns_embedded_link_connect(ma,db,&ib,3600010,id)==RNS_OK);
    transfer(&a,ma,mb,3600011);transfer(&b,mb,ma,3600013);
    frame rtt=pop(&a);a.reject_enqueue=true;
    rns_embedded_link_tx_complete(ma,rtt.id,RNS_OK,3600015);
    assert(rns_embedded_link_state(ma,id,&state)==RNS_ERROR_NOT_FOUND);
    a.reject_enqueue=false;
    assert(rns_embedded_link_connect(ma,db,&ib,3600020,id)==RNS_OK);
    rns_embedded_link_poll(ma,10);
    assert(rns_embedded_link_state(ma,id,&state)==RNS_ERROR_NOT_FOUND);
    assert(rns_embedded_link_connect(ma,db,&ib,11,id)==RNS_OK);
    rns_embedded_link_destroy(ma);rns_embedded_link_destroy(mb);rns_interface_destroy(ifa);rns_interface_destroy(ifb);
    return 0;
}
