#include "reticulum/lxmf_peer_store.h"
#include <assert.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

static bool count_peer(void *ctx,const lxmf_peer_t *p){(*(size_t *)ctx)++;assert(p->address[0]!=0);return true;}
static void set_text(char *dst,size_t *len,const char *src){*len=strlen(src);memcpy(dst,src,*len+1);}
static void put16(uint8_t *p,uint16_t v){p[0]=(uint8_t)(v>>8);p[1]=(uint8_t)v;}
static void put32(uint8_t *p,uint32_t v){p[0]=(uint8_t)(v>>24);p[1]=(uint8_t)(v>>16);p[2]=(uint8_t)(v>>8);p[3]=(uint8_t)v;}
static void put64(uint8_t *p,uint64_t v){for(unsigned i=0;i<8;i++)p[7-i]=(uint8_t)(v>>(i*8));}
static uint32_t crc32_bytes(const uint8_t *p,size_t n){uint32_t c=0xffffffffu;while(n--){c^=*p++;for(unsigned i=0;i<8;i++)c=(c>>1)^(0xedb88320u&(~(c&1u)+1u));}return ~c;}

static void test_v1_store_migrates(void){char path[]="/tmp/lxmf-peers-v1-XXXXXX";int fd=mkstemp(path);assert(fd>=0);uint8_t payload[63]={0};payload[0]=0x6au;payload[16]=LXMF_PEER_TRUST_TRUSTED;payload[19]=LXMF_PEER_PROPAGATION_PREFERRED;payload[20]=1u;payload[22]=0x7bu;put64(payload+38,321u);put64(payload+46,UINT64_C(0x1122334455667788));put32(payload+50,9u);put16(payload+54,1u);put16(payload+56,1u);put16(payload+58,1u);memcpy(payload+60,"Nxd",3u);uint8_t header[24]={0};memcpy(header,"LXPEERS\0",8u);put16(header+8,1u);put16(header+10,24u);put32(header+12,1u);put32(header+16,sizeof payload);put32(header+20,crc32_bytes(payload,sizeof payload));assert(write(fd,header,sizeof header)==(ssize_t)sizeof header);assert(write(fd,payload,sizeof payload)==(ssize_t)sizeof payload);assert(close(fd)==0);lxmf_peer_store_t store={0};assert(lxmf_peer_store_open(&store,path)==LXMF_OK);uint8_t address[16]={0x6au};lxmf_peer_t peer={0};assert(lxmf_peer_store_get(&store,address,&peer)==LXMF_OK);assert(peer.last_seen_ms==321u);assert(peer.last_announce_ms==UINT64_C(0x1122334400000009));assert(peer.unread_count==9u);assert(!strcmp(peer.display_name,"N")&&!strcmp(peer.note,"x")&&!strcmp(peer.draft,"d"));assert(lxmf_peer_store_save(&store)==LXMF_OK);lxmf_peer_store_close(&store);assert(lxmf_peer_store_open(&store,path)==LXMF_OK);assert(lxmf_peer_store_get(&store,address,&peer)==LXMF_OK);assert(peer.last_announce_ms==UINT64_C(0x1122334400000009)&&peer.unread_count==9u);lxmf_peer_store_close(&store);assert(unlink(path)==0);}

int main(void){test_v1_store_migrates();char path[]="/tmp/lxmf-peers-XXXXXX";int fd=mkstemp(path);assert(fd>=0);close(fd);unlink(path);lxmf_peer_store_t s={0};assert(lxmf_peer_store_open(&s,path)==LXMF_OK);lxmf_peer_t p={0};p.address[0]=7;p.trust=LXMF_PEER_TRUST_TRUSTED;p.blocked=true;p.pinned=true;p.propagation=LXMF_PEER_PROPAGATION_PREFERRED;p.has_propagation_node=true;p.propagation_node[0]=9;p.last_seen_ms=123;p.last_announce_ms=100;p.unread_count=4;set_text(p.display_name,&p.display_name_len,"Rei ð¸");set_text(p.note,&p.note_len,"met on Nomad");set_text(p.draft,&p.draft_len,"unfinished message");bool changed=false;assert(lxmf_peer_store_put(&s,&p,&changed)==LXMF_OK&&changed);assert(lxmf_peer_store_save(&s)==LXMF_OK);lxmf_peer_store_close(&s);assert(lxmf_peer_store_open(&s,path)==LXMF_OK&&lxmf_peer_store_count(&s)==1);lxmf_peer_t got;assert(lxmf_peer_store_get(&s,p.address,&got)==LXMF_OK);assert(got.trust==p.trust&&got.blocked&&got.pinned&&got.unread_count==4);assert(got.propagation==p.propagation&&got.has_propagation_node);assert(!memcmp(got.propagation_node,p.propagation_node,sizeof got.propagation_node));assert(got.last_seen_ms==p.last_seen_ms&&got.last_announce_ms==p.last_announce_ms);assert(!strcmp(got.display_name,p.display_name)&&!strcmp(got.note,p.note)&&!strcmp(got.draft,p.draft));size_t count=0;assert(lxmf_peer_store_list(&s,count_peer,&count)==LXMF_OK&&count==1);p.unread_count=0;assert(lxmf_peer_store_put(&s,&p,&changed)==LXMF_OK&&!changed);assert(lxmf_peer_store_save(&s)==LXMF_OK);lxmf_peer_store_close(&s);
/* A corrupt main snapshot is recovered from a complete temporary snapshot. */
char tmp[sizeof path+4];snprintf(tmp,sizeof tmp,"%s.tmp",path);assert(rename(path,tmp)==0);fd=open(path,O_CREAT|O_WRONLY|O_TRUNC,0600);assert(fd>=0&&write(fd,"bad",3)==3);close(fd);assert(lxmf_peer_store_open(&s,path)==LXMF_OK);assert(lxmf_peer_store_get(&s,p.address,&got)==LXMF_OK&&got.unread_count==0);lxmf_peer_store_close(&s);
/* Invalid UTF-8 and overlong declared strings are rejected before mutation. */
assert(lxmf_peer_store_open(&s,path)==LXMF_OK);p.display_name[0]=(char)0xc0;p.display_name[1]=(char)0x80;p.display_name[2]='\0';p.display_name_len=2;assert(lxmf_peer_store_put(&s,&p,NULL)==LXMF_ERR_ARGUMENT);memset(&p,0,sizeof p);p.address[0]=8;p.display_name_len=LXMF_PEER_NAME_MAX+1;assert(lxmf_peer_store_put(&s,&p,NULL)==LXMF_ERR_ARGUMENT);bool removed=false;uint8_t address[16]={7};assert(lxmf_peer_store_remove(&s,address,&removed)==LXMF_OK&&removed);assert(lxmf_peer_store_save(&s)==LXMF_OK);lxmf_peer_store_close(&s);unlink(path);return 0;}
